version: "3"


services:
  db:
    image: mysql
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
  app:
    depends_on:
      - db
    build:
      context: .
    entrypoint:
        - uwsgi
        - --ini
        - uwsgi.ini
    volumes:
    - ./:/app
    ports:
    - "80:5000"
    environment:
      - FLASK_APP=app.py


